#!/bin/bash

##############################################################################
# Script Name	: pi3ctrl-add-ssid
# Description	: Add a wireless network using Network-Manager (RPi Bookworm).
# Args          : <ssid> <passphrase>
# Author       	: Pieter Smets
# Email         : mail@pietersmets.be
##############################################################################

# Set script name
SCRIPT="pi3ctrl-add-ssid"

# Message to display when bad usage.
##############################################################################
# Function: badUsage
# Description: Displays usage information for the script.
##############################################################################
function badUsage {
    local message="$1"
    local txt=(
"Connect to a wireless network providing the ssid and the passphrase."
"Usage: $SCRIPT <ssid> <passphrase>"
    )

    [[ $message ]] && printf "\n$message\n"

    printf "%s\n" "${txt[@]}"
    exit -1
}

##############################################################################
# Function: isRaspberryPi
# Description: Ensures the script is running on a Raspberry Pi.
##############################################################################
function isRaspberryPi {
    local pi=""
    if [ -f /proc/device-tree/model ];
    then
        pi=$( cat /proc/device-tree/model | tr '\0' '\n' | grep "Raspberry Pi" )
    fi
    if [ "x${pi}" == "x" ];
    then
        echo "Error: device is not a Raspberry Pi!"
        exit 1
    fi
}
isRaspberryPi

##############################################################################
# Function: isRoot
# Description: Ensures the script is running with root privileges.
##############################################################################
function isRoot {
    if [ "$EUID" != "0" ]; then
        echo "Error: should be run as root"
        exit 1
    fi
}
isRoot

# Check input arguments
if (($# != 2 )); then
    badUsage "Illegal number of arguments"
fi
if (("${#1}" < 1 )) | (("${#1}" > 63)); then
    badUsage "ssid should be 1..63 characters."
fi
if (("${#2}" < 8 )) | (("${#2}" > 63)); then
    badUsage "passphrase should be 8..63 characters."
fi

# Add ssid with password to Network-Manager 
nmcli d wifi connect "$1" password "$2"

# Trigger connection
sudo systemctl start pi3ctrl-wifi.service

# Done
exit 0
