#!/bin/bash

##############################################################################
# Script Name	: append_wpa_supplicant
# Description	: Append an ssid and the auto-encrypted passphrase to the
#                 wpa_supplicant configuration file.
# Args          : <ssid> <passphrase>
# Author       	: Pieter Smets
# Email         : mail@pietersmets.be
##############################################################################

# Set script name
SCRIPT="append_wpa_supplicant"

# Init
WPA_CONF="/etc/wpa_supplicant/wpa_supplicant.conf"

# Message to display when bad usage.
function badUsage
{
    local message="$1"
    local txt=(
"Append an ssid and the auto-encrypted passphrase to the wpa_supplicant configuration file."
"Usage: $SCRIPT <ssid> <passphrase>"
    )

    [[ $message ]] && printf "\n$message\n"

    printf "%s\n" "${txt[@]}"
    exit -1
}

#
# Check if device is a Raspberry Pi
#
function isRaspberryPi
{
    local pi=""
    if [ -f /proc/device-tree/model ];
    then
        pi=$( cat /proc/device-tree/model | tr '\0' '\n' | grep "Raspberry Pi" )
    fi
    if [ "x${pi}" == "x" ];
    then
        echo "Error: device is not a Raspberry Pi!"
        exit 1
    fi
}
isRaspberryPi

# Check input arguments
if (($# != 2 )); then
    badUsage "Illegal number of arguments"
fi
if ((${#1} < 1 )) | ((${#1} > 63)); then
    badUsage "ssid should be 1..63 characters."
fi
if ((${#2} < 8 )) | ((${#2} > 63)); then
    badUsage "passphrase should be 8..63 characters."
fi

# Add empty line if wpa_supplicant.conf exists
if [ -f $WPA_CONF ];
then
    echo "" | /usr/bin/sudo /usr/bin/tee -a $WPA_CONF
else
    badUsage "wpa_supplicant configuration file \"$WPA_CONF\" does not exist!"
fi

# Encrypt psk and add to wpa_supplicant.conf
wpa_passphrase $1 $2 | sed '3d;2i\\tkey_mgmt=WPA-PSK\n\tpriority=0' | sudo tee -a $WPA_CONF

# Trigger connection
sudo systemctl start multi-ear-wifi.service

# Done
exit 0
